config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search', as: 'search'
  # get 'relationships/create'
  # get 'relationships/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
# これのおかげで最初に動く:メールを送るため

  # 順番上にあげた
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加　多分不要
    get :followers, on: :member # 追加　多分不要
    # get :search, on: :collection
  end

  resources :chats, only: [:create, :show]
  resources :rooms, only: [:create]
  # ここだけ記事と少し違って、chatのshow…いや別にいいのか、アクションでチャットをするとかいう謎の記述だったし？でも一応


  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    # get :search, on: :collection
    # GET /books/searchでBooksコントローラのsearch アクションにルーティングされるようになります。
  end
  

  # 直るまでコメントアウト

  root 'home#top'
  get 'home/about'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
		@book = Book.new

		# @bookid = Book.find(params[:book_id])
		# 本 とりあえず
		if params[:word].present? && params[:model] === "Book" && params[:search] === "perfect"
			@books = Book.where('title LIKE ?', "#{params[:word]}") 
			# 完全一致

		elsif params[:word].present? && params[:model] === "Book" && params[:search] === "front"
			@books = Book.where('title LIKE ?', "#{params[:word]}%")
			# 前方一致

		elsif params[:word].present? && params[:model] === "Book" && params[:search] === "back"
			@books = Book.where('title LIKE ?', "%#{params[:word]}")
			# 後方一致

		elsif params[:word].present? && params[:model] === "Book" && params[:search] === "part"
			@books = Book.where('title LIKE ?', "%#{params[:word]}%")
			# 部分一致
		else
      # @books = Book.none
		end
		
		# user
		if params[:word].present? && params[:model] === "User" && params[:search] === "perfect"
			@users = User.where('name LIKE ?', "#{params[:word]}")
			# 完全一致

		elsif params[:word].present? && params[:model] === "User" && params[:search] === "front"
			@users = User.where('name LIKE ?', "#{params[:word]}%")
			# 前方一致

		elsif params[:word].present? && params[:model] === "User" && params[:search] === "back"
			@users = User.where('name LIKE ?', "%#{params[:word]}")
			# 後方一致

		elsif params[:word].present? && params[:model] === "User" && params[:search] === "part"
			@users = User.where('name LIKE ?', "%#{params[:word]}%")
			# 部分一致
		else
      # @users = User.none
    end
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_search.html.erb
<div class="text-center" style="margin-top:80px">
<%= form_with url: search_path, method: :get, local: true do |f| %>
<!-- あとで行き先変えないと -->
<%= f.text_field :word %>
<!-- こんな検索ワードをまたはなんかできるの？ →できなかった -->
<%= select_tag "model", options_for_select([["User", "User"],["Book","Book"]]) %>
<%= select_tag "search", options_for_select([["完全一致", "perfect"],["前方一致","front"],["後方一致","back"],["部分一致","part"]]) %>
<%= f.submit :search %>
<% end %>
</div>

app/views/search/search.html.erb
<!-- 一旦本だけ -->

<div class="container">

  <div class="row">
    <div class="col-xs-3">

      <h2>User info</h2>
      <%= render 'users/profile', user: current_user %>
      <!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

      <h2>New book</h2>
      <%= render 'books/newform', book: @book %>
    </div>

    <% if @books %>
    <div class="col-xs-9">
      <h2>Books</h2>
      <!--books一覧 -->
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to(book.user) do %>
              <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
              <% end %>
            </td>
            <td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
            <td><%= book.body %></td>

            <%= render 'books/post', book: book %>
            <%# いいね機能をここに書くが、idどうやって渡すか考える eachの中だからそのままでいいのでは %>

            <td>
              <p>コメント数：<%= book.book_comments.count %></p>
            </td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!--books一覧 -->
    <% end %>

    <% if @users %>
    <div class="col-xs-9">
      <h2>Users</h2>
      <!--users一覧 -->
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
            <td><%= user.name%></td>
            <td>
              <p>フォロー数：<%= user.followings.count %></p>
            </td>
            <td>
              <p>フォロワー数：<%= user.followers.count %></p>
            </td>
            <td><% if current_user != user %>
              <% if user.followed_by?(current_user) %>
              <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
              <% else %>
              <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
              <% end %>
              <% end %></td>
            <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>

</div>