config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search', as: 'search'
  # get 'relationships/create'
  # get 'relationships/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
# これのおかげで最初に動く:メールを送るため

  # 順番上にあげた
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加　多分不要
    get :followers, on: :member # 追加　多分不要
    # get :search, on: :collection
  end

  resources :chats, only: [:create, :show]
  resources :rooms, only: [:create]
  # ここだけ記事と少し違って、chatのshow…いや別にいいのか、アクションでチャットをするとかいう謎の記述だったし？でも一応


  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    # get :search, on: :collection
    # GET /books/searchでBooksコントローラのsearch アクションにルーティングされるようになります。
  end
  

  # 直るまでコメントアウト

  root 'home#top'
  get 'home/about'
end

app/models/user.rb
class User < ApplicationRecord

before_validation :full_adress_sign_up
# 住所登録用


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

# // app/models/user.rb に追記
include JpPrefecture
jp_prefecture :prefecture_code  
# // prefecture_codeはuserが持っているカラム


# // postal_codeからprefecture_nameに変換するメソッドを用意します．
def prefecture_name
  JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
end

def prefecture_name=(prefecture_name)
  self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
end

# ここにアドレスを足算させる user.full_adressで呼び出せる
def full_address
  prefecture_code + city + building
end

# 地図表示用一旦Cityのみ、後から三つ
geocoded_by :prefecture_code
after_validation :geocode

  attachment :profile_image
  # , destroy: false　怪しいから削除　あるよなぁ

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # チャット用
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50 }

  private
  def full_adress_sign_up
    self.full_address = prefecture_code + city + building
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    binding.pry
    # 親（右:Devise）のcreateを呼ぶ

    UserMailer.thanks(current_user).deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user! 
	before_action :baria_user, only: [:edit,:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
		@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）、書いてあった
		
		@users = User.all #仮

    @currentUserEntry = UserRoom.where(user_id: current_user.id)
		@userEntry = UserRoom.where(user_id: @user.id)
		# ルームを作った方（押した方）と、ルームを作られる方（押された方）の情報を格納

		unless @user.id == current_user.id
			# showページがマイページではない場合（前提）
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
					# すでにルームがある場合とない場合のif
					if cu.room_id == u.room_id then
						# すでに作成されているルームを特定、どっちがどっちに入ろうと同じということ？
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = UserRoom.new
      end
		end
		
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）？
	end
	
	def edit
		@user = User.find(params[:id])
	end

  def update
		@user = User.find(params[:id])
		
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render action: :edit
  	end
	end
	
	# ==============追加================
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
# ==============追加================

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%=link_to user.followings.count, follows_user_path(user.id) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th><%=link_to user.followers.count, followers_user_path(user.id) %></th>
		</tr>

</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>


<% if current_user != user %>
    <% if user.followed_by?(current_user) %>
        <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
    <% else %>
        <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
    <% end %>
<% end %>
<!--ここまで -->

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit "Update User" %>
</div>

<% end %>

app/views/users/followers.html.erb
<% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/follows.html.erb
<% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<!---->
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>


		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td>
							<p>フォロー数：<%= user.followings.count %></p>
						</td>
						<td>
							<p>フォロワー数：<%= user.followers.count %></p>
						</td>
						<td><% if current_user != user %>
							<% if user.followed_by?(current_user) %>
							<p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
							<% else %>
							<p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
							<% end %>
							<% end %></td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<!--users一覧 -->

	</div>
</div>

app/views/users/show.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可　？ -->

			<!-- チャット用 -->
			<% unless @user.id == current_user.id %>
			<% if @isRoom == true %>
			<p class="user-show-room"><a href="/chats/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
				<% else %>
				<%= form_for @room do |f| %>
				<%= fields_for @entry do |e| %>
				<%= e.hidden_field :user_id, value: @user.id %>
				<% end %>
				<%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
				<% end %>
				<% end %>
				<% end %>

				<h2>New book</h2>
				<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>
</div>
<!--books一覧 -->

<% if @user = current_user%>
<div id="map"></div>
<% end %>

<style>
	#map {
		height: 600px;
		width: 80%;
		margin-left: 200px;
		margin-top: 50px;
		margin-bottom: 50px;
	}
</style>


<!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyAOhLA-VsPczm3kPTXq-Q69__jS9a-rcwI&callback=initMap -->
<!-- async: true, defer: true -->

<script>
	function initMap() {
		var latlng = {
			lat: < %= @user.latitude % > ,
			lng: < %= @user.longitude % >
		};
		var contentString = '<%= @user.full_address %>';
		// PINを挿す位置を決める
		var map = new google.maps.Map(document.getElementById('map'), {
			zoom: 15,
			center: latlng
			// 初期の位置
		});
		var transitLayer = new google.maps.TransitLayer();
		transitLayer.setMap(map);


		var infowindow = new google.maps.InfoWindow({
			content: contentString
		});

		var marker = new google.maps.Marker({
			position: latlng,
			map: map,
			title: contentString
		});

		marker.addListener('click', function () {
			infowindow.open(map, marker);
		});
	}
</script>



<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['KEY']%>&callback=initMap"> </script>