config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search', as: 'search'
  # get 'relationships/create'
  # get 'relationships/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
# これのおかげで最初に動く:メールを送るため

  # 順番上にあげた
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加　多分不要
    get :followers, on: :member # 追加　多分不要
    # get :search, on: :collection
  end

  resources :chats, only: [:create, :show]
  resources :rooms, only: [:create]
  # ここだけ記事と少し違って、chatのshow…いや別にいいのか、アクションでチャットをするとかいう謎の記述だったし？でも一応


  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    # get :search, on: :collection
    # GET /books/searchでBooksコントローラのsearch アクションにルーティングされるようになります。
  end
  

  # 直るまでコメントアウト

  root 'home#top'
  get 'home/about'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	# いいねで使う用のもの


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user! 
	before_action :correct_user, only: [:edit, :update]


  def show
		@book = Book.find(params[:id])
		@user = @book.user
		@books = Book.new

		@book_comment = BookComment.new
		# あっているかも

		# コメントフォームの初期値　無理だった
		@value = ""
  end

  def index
		@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall あれ、これがある、、、ないと思った
		@book = Book.new

		# @bookn = Book.find(params[:id])
		# コメント数を表示させるため新たに記載→each文の中だからいらないかも
  end

  def create
		@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
		@book.user_id = current_user.id
    # 意味：user_idがnilのままだと、子モデルのbookの方が保存できない
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
			@books = Book.all
  		render action: :index
  	end
  end

  def edit
		@book = Book.find(params[:id])
		

  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
			render "edit"
			
  	end
  end

  def delete
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
	end
	

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

	def correct_user
    @book = Book.find(params[:id])
    # まず本を取り出した 重要
    @user = @book.user
    # 本に結びついたユーザーを取り出す
    if current_user != @user
      redirect_to books_path
    # 正しいユーザーではない場合本一覧に戻す
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
	<%# trの上に書く %>
	<table class="table">
	<% book.book_comments.each do |book_comment|%>
<tr>
	<td>
		<%= link_to attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg"), user_path(book_comment.user) %>
		<%= book_comment.user.name %>
	</td>
	<td>
		<%= book_comment.comment %>
	</td>

	<td>
		<% if book_comment.user_id == current_user.id %>
		<%= link_to "Delete", book_book_comment_path(book,book_comment.id), method: :delete, class: "btn-sm btn-danger",remote: true %>
		<br>
		<% end %>
	</td>
</tr>
 <% end %>

 </table>

app/views/books/_newform.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_post.html.erb
<%# いいね機能 %>
<td id="favorite-<%= book.id %>">
  <% if book.favorited_by?(current_user) %>
  <!-- もしファボっていたら、だからデリートから描く -->
  <%= link_to book_favorites_path(book), method: :delete , remote: true do %>
  <i class="fa fa-heart" aria-hidden="true" style="color: pink;"></i>
  <%= book.favorites.count %>
  <% end %>
  <% else %>
  <%= link_to book_favorites_path(book), method: :post , remote: true do %>
  <i class="fa fa-heart-o" aria-hidden="true"></i>
  <%= book.favorites.count %>
  <% end %>
  <% end %>
</td>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>

<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ 右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>


		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>

							<%# いいねの部分 %>
							<%= render 'books/post', book: book%>
							<%# もう触らない %>


						<td>
							<p>コメント数：<%= book.book_comments.count %></p>
						</td>

					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<!--books一覧 -->

	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @books %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<td>
						<%= render 'books/post', book: @book%>
						<%# いいね機能 %>
					</td>

					<!-- コメント数表示機能 -->
					<td>
						<p>コメント数：<%= @book.book_comments.count %></p>
					</td>

					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td>
						<%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
					</td>
					<% end %>
				</tr>
			</table>

				<%# コメント非同期 %>
			<div id="comment-<%= @book.id %>">
			<%# クラスを渡したい %>
				<%= render 'books/comment', book: @book %>
			</div>


			<!-- 投稿したコメントと書く場所表示 -->

			<div class="post-comment">
				<%= form_with(model:[@book,@book_comment], remote: true, method: :post, value: "") do |f| %>
				<%# ここで非同期にする local true doを消した！ %>
				<%= f.text_area :comment, size: "80x10" %><br>
				<!-- :の後はカラム名 -->
				<%= f.submit "送信する" %>
				<% end %>
			</div>

		</div>
	</div>
</div>